server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  main:
    allow-bean-definition-overriding: true
activiti:
  check-process-definitions: true
  database-schema-update: true
  history-level: full
thymeleaf:
  mode: HTML
  encoding: utf-8
  cache: false
application:
  name: actdemo
mvc:
  static-path-pattern: /static/**